use std::collections::BTreeMap;

use serde::Serialize;
use syn::{FnArg, Item, ReturnType, Type, Visibility};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Info,
    Warning,
    Error,
}

#[derive(Debug, Clone, Serialize)]
pub struct Finding {
    pub severity: Severity,
    pub rule_id: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suggested_fix: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ValidationReport {
    pub valid: bool,
    pub findings: Vec<Finding>,
}

pub fn validate_implementation(
    code: &str,
    path: Option<&str>,
    kind: Option<&str>,
) -> ValidationReport {
    let mut findings = Vec::new();
    let is_rust = kind == Some("rust")
        || path
            .map(|path| path.ends_with(".rs"))
            .unwrap_or_else(|| looks_like_rust(code));
    let is_html = kind == Some("html")
        || path
            .map(|path| path.ends_with(".html"))
            .unwrap_or_else(|| !is_rust);

    if is_rust {
        validate_rust(code, path, kind, &mut findings);
    }
    if is_html {
        validate_html(code, path, &mut findings);
    }

    let valid = !findings
        .iter()
        .any(|finding| finding.severity == Severity::Error);
    ValidationReport { valid, findings }
}

fn validate_rust(code: &str, path: Option<&str>, kind: Option<&str>, findings: &mut Vec<Finding>) {
    // Scan text lines first for quick checks with line numbers
    for (idx, line) in code.lines().enumerate() {
        let lnum = idx + 1;
        let line_lower = line.to_ascii_lowercase();

        for directive in [
            "s-boost",
            "s-target",
            "s-swap",
            "s-trigger",
            "client:",
            "<Island",
        ] {
            if line.contains(directive) {
                findings.push(finding_with_line(
                    Severity::Error,
                    "pilcrow-boundary-silcrow-in-rust",
                    format!("Silcrow/client directive `{directive}` belongs in HTML templates, not Rust code."),
                    path,
                    Some(lnum),
                    Some("crates/runtime/assets/silcrow.js — directives are HTML-only"),
                    Some("Move the directive to the paired .html template."),
                ));
            }
        }

        // Nudge: hard-coded URL strings in redirect/navigate → suggest typed routes::
        if !line_lower.contains("//") {
            if let Some(url) = extract_redirect_url(line) {
                findings.push(finding_with_line(
                    Severity::Info,
                    "pilcrow-typed-routes-suggestion",
                    format!("Hard-coded URL `{url}` — consider using a generated `routes::` helper for compile-time safety."),
                    path,
                    Some(lnum),
                    Some("crates/routekit/src/templating/routes_codegen.rs"),
                    Some("Use `routes::products()` for static routes or `routes::products_id(&id)` for dynamic. Both are generated by pilcrow_app!()."),
                ));
            }
        }

        // Nudge: Ok(StatusCode::OK.into_response()) → ok()
        if line.contains("StatusCode::OK.into_response()") && !line_lower.contains("//") {
            findings.push(finding_with_line(
                Severity::Info,
                "pilcrow-use-ok-helper",
                "Use `ok()` instead of `Ok(StatusCode::OK.into_response())` — shorter and supports chaining via ActionResultExt.".to_string(),
                path,
                Some(lnum),
                Some("crates/runtime/src/response/response.rs"),
                Some("ok() returns ActionResult directly. Chain modifiers: ok().with_toast(\"Done\", ToastLevel::Success)."),
            ));
        }

        // Warn on direct std::env::var access when env-config may be appropriate
        if line.contains("std::env::var(") || line.contains("env::var(") {
            if !line_lower.contains("//") {
                findings.push(finding_with_line(
                    Severity::Info,
                    "pilcrow-env-direct-access",
                    "Direct env::var() usage detected. Consider typed env config via Pilcrow.toml [env] and generated env::Public/Private helpers.".to_string(),
                    path,
                    Some(lnum),
                    Some("crates/routekit/src/templating/build_config.rs"),
                    Some("Add env vars to Pilcrow.toml [env] and use generated env::Private::load()."),
                ));
            }
        }

        // Detect removed/unsupported static-output constants.
        for unsupported_const in ["GENERATE_STATIC_PARAMS"] {
            if line.contains(unsupported_const) && line.contains("const") {
                findings.push(finding_with_line(
                    Severity::Error,
                    "pilcrow-planned-static-output",
                    format!("`{unsupported_const}` is not supported in Pilcrow. Use `pub const PROMOTE_AFTER: u32 = 0;` for bake-on-first-hit."),
                    path,
                    Some(lnum),
                    Some("registry.toml: feature ssg"),
                    Some("Use `pub const PROMOTE_AFTER: u32 = 0;` in your code-behind to bake on first hit."),
                ));
            }
        }

        // PROMOTE_AFTER on a dynamic route: warn that it is incoherent for open ID-spaces.
        if line.contains("PROMOTE_AFTER") && line.contains("const") {
            let has_path_param = code.contains("Path(") || code.contains("req.params");
            if has_path_param {
                findings.push(finding_with_line(
                    Severity::Warning,
                    "pilcrow-fsr-promote-after-dynamic-route",
                    "PROMOTE_AFTER on a dynamic route (route with path params) is typically incoherent. Every distinct URL gets its own pilcrow_fsr row; with an open ID-space (e.g. /contacts/[id]) each URL is immediately marked promoted=TRUE but html_path remains NULL — the watcher will log warnings for missing baked files on every invalidation cycle.".to_string(),
                    path,
                    Some(lnum),
                    Some("registry.toml: feature fsr"),
                    Some("Remove PROMOTE_AFTER from dynamic routes. Reserve it for static or near-static routes (e.g. /, /about) where the set of URL instances is finite and known at startup."),
                ));
            }
        }

        // PRERENDER is removed — build error. Use PROMOTE_AFTER = 0 instead.
        if line.contains("PRERENDER") && line.contains("const") {
            findings.push(finding_with_line(
                Severity::Error,
                "pilcrow-prerender-removed",
                "`PRERENDER: bool` is removed. Use `pub const PROMOTE_AFTER: u32 = 0;` instead.".to_string(),
                path,
                Some(lnum),
                Some("registry.toml: feature ssg"),
                Some("Replace `pub const PRERENDER: bool = true;` with `pub const PROMOTE_AFTER: u32 = 0;`."),
            ));
        }

        // STREAMING conflicts: detect incompatible const combinations at build time.
        if line.contains("STREAMING") && line.contains("const") {
            if code.contains("REVALIDATE") {
                findings.push(finding_with_line(
                    Severity::Error,
                    "pilcrow-streaming-isr-conflict",
                    "STREAMING = true is incompatible with REVALIDATE — routekit reports this as a structured build error.".to_string(),
                    path,
                    Some(lnum),
                    Some("registry.toml: feature SSR Streaming"),
                    Some("Use FSR LiveProp fields for surgical live updates, or split slow UI into an island/fragment instead of enabling STREAMING on ISR."),
                ));
            }
            if code.contains("LiveProp<") {
                findings.push(finding_with_line(
                    Severity::Error,
                    "pilcrow-streaming-fsr-conflict",
                    "STREAMING = true is incompatible with FSR (inline Live / LiveProp) — routekit reports this as a structured build error.".to_string(),
                    path,
                    Some(lnum),
                    Some("registry.toml: feature fsr"),
                    Some("FSR routes serve pre-baked HTML with surgical slot patches. Remove STREAMING = true, or remove the inline Live/LiveProp fields."),
                ));
            }
            if code.contains("FSR_JSON") {
                findings.push(finding_with_line(
                    Severity::Error,
                    "pilcrow-streaming-fsr-json-conflict",
                    "STREAMING = true is incompatible with FSR_JSON = true — routekit reports this as a structured build error.".to_string(),
                    path,
                    Some(lnum),
                    Some("registry.toml: feature fsr"),
                    Some("Baked JSON output requires a promoted (non-streaming) route. Remove FSR_JSON = true from streaming pages."),
                ));
            }
        }
    }

    // LiveProp<T> field type check hint.
    if code.contains("LiveProp<") {
        // Warn if the type parameter looks like it might not be Sync (e.g. Rc<T> or RefCell<T>).
        if code.contains("Rc<") || code.contains("RefCell<") || code.contains("Cell<") {
            findings.push(finding(
                Severity::Error,
                "pilcrow-live-prop-not-sync",
                "LiveProp<T> requires T: Sync. Types like Rc<T>, RefCell<T>, and Cell<T> are not Sync and cannot be used as LiveProp type parameters.".to_string(),
                path,
                Some("registry.toml: feature live-props"),
                Some("Use Arc<Mutex<T>> or a plain T that is Sync instead."),
            ));
        }
    }

    // ISR safety: if REVALIDATE is enabled and handler code reads request-scoped values,
    // recommend CACHE_VARY to avoid cross-context cache reuse.
    if code.contains("REVALIDATE")
        && !code.contains("CACHE_VARY")
        && (code.contains("req.cookies")
            || code.contains("req.headers")
            || code.contains("req.locale")
            || code.contains("req.locals"))
    {
        findings.push(finding(
            Severity::Warning,
            "pilcrow-isr-missing-cache-vary",
            "REVALIDATE is set and request-scoped values are used, but CACHE_VARY is not declared. This can cause cache key collisions across users/locales.".to_string(),
            path,
            Some("registry.toml: feature incremental-ssr"),
            Some("Add `pub const CACHE_VARY: &[&str] = &[\"session\", \"accept-language\"];` (or relevant keys) in the page code-behind."),
        ));
    }

    if kind != Some("api")
        && (code.contains("Router::new().route(") || code.contains(".route("))
        && !code.contains("pub fn router()")
    {
        findings.push(finding(
            Severity::Warning,
            "pilcrow-no-manual-route-registration",
            "Page routes should be discovered by Pilcrow routekit instead of manually registered."
                .to_string(),
            path,
            Some("crates/routekit/src/templating/codegen/app_module.rs"),
            Some("Use pilcrow_web::include_generated_app!() and let routekit register pages."),
        ));
    }

    let parsed = match syn::parse_file(code) {
        Ok(file) => file,
        Err(error) => {
            findings.push(finding(
                Severity::Error,
                "rust-parse-error",
                format!("Rust snippet does not parse: {error}"),
                path,
                None,
                None,
            ));
            return;
        }
    };

    let is_layout = path.map(|p| p.contains("_layout")).unwrap_or(false);
    let is_ui_component = path
        .map(|p| p.contains("/ui/") || p.contains("\\ui\\"))
        .unwrap_or(false);

    for item in &parsed.items {
        match item {
            Item::Fn(function) => {
                let name = function.sig.ident.to_string();
                if name == "load" {
                    if function.sig.asyncness.is_none() {
                        findings.push(finding(
                            Severity::Error,
                            "pilcrow-load-async",
                            "load must be declared async.".to_string(),
                            path,
                            Some("crates/routekit/src/templating/codegen/instrument.rs"),
                            Some("Use `pub async fn load(req: Req) -> AppResult<Props>` or `pub async fn load(ctx: Page) -> AppResult<Props>` on dynamic pages."),
                        ));
                    }
                    if !returns_named_type(&function.sig.output, "AppResult") {
                        findings.push(finding(
                            Severity::Error,
                            "pilcrow-load-return",
                            "load should return AppResult<Props>.".to_string(),
                            path,
                            Some("crates/routekit/src/templating/codegen/instrument.rs"),
                            Some("Use `-> AppResult<Props>` and return `Ok(Props { ... })`."),
                        ));
                    }
                    if !wants_type(&function.sig.inputs, "Req")
                        && !wants_type(&function.sig.inputs, "Page")
                    {
                        findings.push(finding(
                            Severity::Warning,
                            "pilcrow-load-req",
                            "load should accept a Req argument, or Page on dynamic file routes."
                                .to_string(),
                            path,
                            Some("crates/routekit/src/templating/codegen/instrument.rs"),
                            Some("Use `pub async fn load(req: Req) -> AppResult<Props>` or `pub async fn load(ctx: Page) -> AppResult<Props>`."),
                        ));
                    }
                } else if matches!(function.vis, Visibility::Public(_))
                    && wants_type(&function.sig.inputs, "Req")
                {
                    // Layout and UI components cannot define actions at all
                    if is_layout {
                        findings.push(finding(
                            Severity::Error,
                            "pilcrow-layout-no-actions",
                            format!("Layouts cannot define named action `{name}`. Only load() is permitted in layout code-behind."),
                            path,
                            Some("crates/routekit/src/templating/codegen/instrument.rs"),
                            Some("Remove the action fn from _layout.rs. Move it to the page or fragment code-behind instead."),
                        ));
                    } else if is_ui_component {
                        findings.push(finding(
                            Severity::Error,
                            "pilcrow-component-no-actions",
                            format!("UI components cannot define named action `{name}`. Actions belong in page or fragment code-behind files."),
                            path,
                            Some("crates/routekit/src/templating/codegen/instrument.rs"),
                            Some("Move the action to the page or fragment .rs file that uses this component."),
                        ));
                    } else if !returns_named_type(&function.sig.output, "ActionResult") {
                        findings.push(finding(
                            Severity::Warning,
                            "pilcrow-action-return",
                            format!("public handler `{name}` accepts Req but does not return ActionResult."),
                            path,
                            Some("crates/routekit/src/templating/codegen/instrument.rs"),
                            Some(
                                "Named page/fragment actions should use `pub async fn name(req: Req) -> ActionResult`.",
                            ),
                        ));
                    }
                }
            }
            Item::Const(c) => {
                let name = c.ident.to_string();
                // Validate page option constant values
                if name == "TRAILING_SLASH" {
                    let value_str = quote_const_value(c);
                    if let Some(v) = value_str {
                        if !matches!(v.as_str(), "always" | "never" | "ignore") {
                            findings.push(finding(
                                Severity::Error,
                                "pilcrow-page-option-trailing-slash",
                                format!("TRAILING_SLASH value `{v}` is invalid. Expected: always | never | ignore."),
                                path,
                                Some("crates/routekit/src/templating/page_options.rs"),
                                Some("Use `pub const TRAILING_SLASH: &str = \"always\";` or \"never\" or \"ignore\"."),
                            ));
                        }
                    }
                } else if name == "LAYOUT" {
                    let value_str = quote_const_value(c);
                    if let Some(v) = value_str {
                        if v != "none" {
                            findings.push(finding(
                                Severity::Error,
                                "pilcrow-page-option-layout",
                                format!("LAYOUT value `{v}` is invalid. Only \"none\" is supported."),
                                path,
                                Some("crates/routekit/src/templating/page_options.rs"),
                                Some("Use `pub const LAYOUT: &str = \"none\";` to opt out of layout wrapping."),
                            ));
                        }
                    }
                } else if name == "REVALIDATE" || name == "MAX_STALE" {
                    // Must be an integer literal (u64), not a string like "60"
                    if let syn::Expr::Lit(expr_lit) = c.expr.as_ref() {
                        if matches!(&expr_lit.lit, syn::Lit::Str(_)) {
                            findings.push(finding(
                                Severity::Error,
                                "pilcrow-isr-const-wrong-type",
                                format!("`{name}` must be a u64 integer literal: `pub const {name}: u64 = 60;` — not a string."),
                                path,
                                Some("crates/routekit/src/templating/page_options.rs"),
                                Some("Use a plain integer, e.g. `pub const REVALIDATE: u64 = 60;`."),
                            ));
                        }
                    }
                } else if name == "STREAMING" {
                    // Must be a bool literal, not a string like "true"
                    if let syn::Expr::Lit(expr_lit) = c.expr.as_ref() {
                        if matches!(&expr_lit.lit, syn::Lit::Str(_)) {
                            findings.push(finding(
                                Severity::Error,
                                "pilcrow-streaming-wrong-type",
                                "STREAMING must be a bool literal: `pub const STREAMING: bool = true;` — not a string.".to_string(),
                                path,
                                Some("crates/routekit/src/templating/page_options.rs"),
                                Some("Use `pub const STREAMING: bool = true;` in your .rs code-behind."),
                            ));
                        }
                    }
                }
            }
            _ => {}
        }
    }
}

fn validate_html(code: &str, path: Option<&str>, findings: &mut Vec<Finding>) {
    // Detect the "class trap": s-live on an element whose tag also has a class
    // attribute interpolating the same live field. s-live only patches textContent;
    // the class stays frozen at SSR value after an SSE update.
    for (idx, line) in code.lines().enumerate() {
        let lnum = idx + 1;
        if line.contains("s-live=") && line.contains("class=") && line.contains("live.") {
            // Heuristic: same line has both s-live and a class attr referencing a live field.
            findings.push(finding_with_line(
                Severity::Warning,
                "pilcrow-fsr-s-live-class-trap",
                "Element has both s-live and a class attribute that interpolates a live field value. s-live only patches textContent — the class is rendered at SSR time and will not update on SSE patch. If the live value controls badge colour or other class-dependent styling, use the object path: define a struct with text + class fields and use s-use=\"fsr.<slot>\" instead.".to_string(),
                path,
                Some(lnum),
                Some("docs/Pilcrow-Silcrow Docs/03 Rendering/FSR SSE Hub.md"),
                Some("Replace LiveProp<String> with LiveProp<Badge { text, class }>, mark #[pilcrow::allow_unused], and use s-use=\"fsr.slot\" on the element."),
            ));
        }
    }

    for (slot, count) in collect_s_live_counts(code)
        .into_iter()
        .filter(|(_, count)| *count > 1)
    {
        findings.push(finding(
            Severity::Error,
            "pilcrow-fsr-duplicate-s-live",
            format!(
                "Duplicate FSR slot s-live=\"{slot}\" appears {count} times. Routekit requires each s-live slot name in a template to be unique."
            ),
            path,
            Some("crates/routekit/src/fsr.rs"),
            Some("Use one s-live slot per Live field, or split the values into distinct LiveProp fields."),
        ));
    }

    for (idx, line) in code.lines().enumerate() {
        let lnum = idx + 1;

        // SvelteKit <svelte:head> is not valid Pilcrow syntax.
        if line.contains("<svelte:head") {
            findings.push(finding_with_line(
                Severity::Error,
                "pilcrow-svelte-head-syntax",
                "`<svelte:head>` is SvelteKit syntax. Use `<pilcrow:head>...</pilcrow:head>` instead.".to_string(),
                path,
                Some(lnum),
                Some("registry.toml: feature head-meta (stable)"),
                Some("Wrap your <title>, <meta>, and <link> tags in <pilcrow:head>...</pilcrow:head>. The layout must have <slot name=\"pilcrow_head\"> to receive them."),
            ));
        }

        // Old PascalCase <Island> and client: directives were the planned (never-shipped) API.
        // The stable API is lowercase <island src="..." strategy="...">.
        for directive in [
            "<Island",
            "client:load",
            "client:idle",
            "client:visible",
            "s-island",
        ] {
            if line.contains(directive) {
                findings.push(finding_with_line(
                    Severity::Error,
                    "pilcrow-wrong-island-syntax",
                    format!("`{directive}` is not valid Pilcrow syntax. Use the lowercase <island> tag instead."),
                    path,
                    Some(lnum),
                    Some("registry.toml: feature islands (stable)"),
                    Some("Use `<island src=\"./component\" strategy=\"visible\" />` for co-located islands."),
                ));
            }
        }

        if line.contains("<react") {
            if !line.contains("src=") {
                findings.push(finding_with_line(
                    Severity::Error,
                    "pilcrow-react-missing-src",
                    "`<react>` requires a static src attribute pointing at a React component."
                        .to_string(),
                    path,
                    Some(lnum),
                    Some("registry.toml: feature react-islands (stable)"),
                    Some("Use `<react src=\"./react/Counter.tsx\" strategy=\"visible\" />`."),
                ));
            }
            if !line.contains("strategy=") {
                findings.push(finding_with_line(
                    Severity::Error,
                    "pilcrow-react-missing-strategy",
                    "`<react>` requires strategy=\"load\", \"visible\", or \"idle\" so JavaScript cost is explicit.".to_string(),
                    path,
                    Some(lnum),
                    Some("registry.toml: feature react-islands (stable)"),
                    Some("Prefer `strategy=\"visible\"` for non-critical widgets."),
                ));
            }
        }

        if line.contains("generateStaticParams") {
            findings.push(finding_with_line(
                Severity::Error,
                "pilcrow-planned-static-output",
                "`generateStaticParams` is not supported in Pilcrow. Use `pub const PROMOTE_AFTER: u32 = 0;` in the .rs code-behind.".to_string(),
                path,
                Some(lnum),
                Some("registry.toml: feature ssg"),
                Some("Add `pub const PROMOTE_AFTER: u32 = 0;` in your .rs code-behind file to bake on first hit."),
            ));
        }
        if line.contains("prerender") {
            findings.push(finding_with_line(
                Severity::Warning,
                "pilcrow-prerender-in-html",
                "`prerender` is not a valid HTML attribute. Use `pub const PROMOTE_AFTER: u32 = 0;` in the .rs code-behind instead.".to_string(),
                path,
                Some(lnum),
                Some("registry.toml: feature ssg"),
                Some("Add `pub const PROMOTE_AFTER: u32 = 0;` in your paired .rs file instead."),
            ));
        }
        if line.contains("REVALIDATE") || line.contains("CACHE_TAGS") || line.contains("CACHE_VARY")
        {
            findings.push(finding_with_line(
                Severity::Warning,
                "pilcrow-isr-const-in-html",
                "ISR constants (REVALIDATE, CACHE_TAGS, CACHE_VARY) belong in the .rs code-behind, not the HTML template.".to_string(),
                path,
                Some(lnum),
                Some("registry.toml: feature incremental-ssr"),
                Some("Move ISR constants to the paired .rs file alongside your Props and load() fn."),
            ));
        }

        // Manual SW registration — Pilcrow injects this automatically when service_worker.enabled = true.
        if line.contains("serviceWorker.register") || line.contains("serviceWorker.register") {
            findings.push(finding_with_line(
                Severity::Warning,
                "pilcrow-manual-sw-registration",
                "Manual service worker registration detected. Pilcrow handles this automatically when `[service_worker] enabled = true` is set in Pilcrow.toml.".to_string(),
                path,
                Some(lnum),
                Some("registry.toml: feature service-worker"),
                Some("Remove the manual register() call and add `[service_worker]\\nenabled = true` to Pilcrow.toml."),
            ));
        }

        if line.contains("useState(") || line.contains("onclick=") || line.contains("x-data") {
            findings.push(finding_with_line(
                Severity::Warning,
                "pilcrow-hydration-static-mismatch",
                "This template appears to depend on client-only state or event handlers without an implemented dynamic feature path.".to_string(),
                path,
                Some(lnum),
                Some("CLAUDE.md: silcrow.js section"),
                Some("Prefer server actions, s-boost navigation, or server-rendered fragments."),
            ));
        }

        // Check for Silcrow directives in .rs files (should not be HTML path for these)
        // Validate action paths: ?/name should reference real action names
        if line.contains("action=\"?/") || line.contains("s-post=\"?/") {
            // Just an info note — we cannot verify action names without the RS file here
            // Only emit if the action appears to use whitespace (malformed)
            if let Some(action) = extract_action_name(line) {
                if action.contains(' ') || action.is_empty() {
                    findings.push(finding_with_line(
                        Severity::Error,
                        "pilcrow-invalid-action-name",
                        format!("Action name `?/{action}` is invalid — names must be valid identifiers."),
                        path,
                        Some(lnum),
                        Some("CLAUDE.md: Actions Pattern section"),
                        Some("Use `?/submit` or `?/create` — a valid Rust identifier after the slash."),
                    ));
                }
            }
        }
    }
}

fn collect_s_live_counts(html: &str) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    let mut offset = 0;
    while let Some(pos) = html[offset..].find("s-live") {
        let attr_start = offset + pos;
        let after_name = attr_start + "s-live".len();
        if after_name < html.len()
            && html[after_name..]
                .chars()
                .next()
                .is_some_and(|ch| ch.is_ascii_alphanumeric() || ch == '-' || ch == '_')
        {
            offset = after_name;
            continue;
        }

        let Some((name, next_offset)) = parse_s_live_value(html, after_name) else {
            offset = after_name;
            continue;
        };
        if !name.is_empty() {
            *counts.entry(name).or_insert(0) += 1;
        }
        offset = next_offset;
    }
    counts
}

fn parse_s_live_value(html: &str, mut offset: usize) -> Option<(String, usize)> {
    let bytes = html.as_bytes();
    while offset < bytes.len() && bytes[offset].is_ascii_whitespace() {
        offset += 1;
    }
    if bytes.get(offset) != Some(&b'=') {
        return None;
    }
    offset += 1;
    while offset < bytes.len() && bytes[offset].is_ascii_whitespace() {
        offset += 1;
    }
    let quote = *bytes.get(offset)?;
    if quote != b'"' && quote != b'\'' {
        return None;
    }
    offset += 1;
    let value_start = offset;
    while offset < bytes.len() && bytes[offset] != quote {
        offset += 1;
    }
    if offset >= bytes.len() {
        return None;
    }
    Some((html[value_start..offset].to_string(), offset + 1))
}

/// Extract the URL string from a `redirect("/path")`, `navigate("/path")`, or
/// `AppError::Redirect("/path")` call on a single line. Returns `None` for the
/// root path `"/"` (always fine) and for anything that looks like a variable.
fn extract_redirect_url(line: &str) -> Option<String> {
    for prefix in &["redirect(\"/", "navigate(\"/", "AppError::Redirect(\"/"] {
        if let Some(pos) = line.find(prefix) {
            let url_start = pos + prefix.len() - 1; // include the leading "/"
            let rest = &line[url_start..];
            let end = rest.find('"').unwrap_or(rest.len());
            let url = rest[..end].trim_end_matches('/');
            // Only suggest routes:: for non-root paths with at least one segment
            if url.len() > 1 && !url.contains('{') {
                return Some(url.to_string());
            }
        }
    }
    None
}

fn extract_action_name(line: &str) -> Option<String> {
    // Match ?/name in action= or s-post=
    let pos = line.find("?/")?;
    let rest = &line[pos + 2..];
    let end = rest
        .find(|c: char| !c.is_alphanumeric() && c != '_')
        .unwrap_or(rest.len());
    Some(rest[..end].to_string())
}

fn quote_const_value(c: &syn::ItemConst) -> Option<String> {
    if let syn::Expr::Lit(expr_lit) = c.expr.as_ref() {
        if let syn::Lit::Str(lit_str) = &expr_lit.lit {
            return Some(lit_str.value());
        }
    }
    None
}

fn returns_named_type(output: &ReturnType, expected: &str) -> bool {
    let ReturnType::Type(_, ty) = output else {
        return false;
    };
    type_contains_name(ty, expected)
}

fn wants_type(
    inputs: &syn::punctuated::Punctuated<FnArg, syn::token::Comma>,
    expected: &str,
) -> bool {
    inputs.iter().any(|arg| {
        let FnArg::Typed(arg) = arg else {
            return false;
        };
        type_contains_name(&arg.ty, expected)
    })
}

fn type_contains_name(ty: &Type, expected: &str) -> bool {
    match ty {
        Type::Path(path) => path
            .path
            .segments
            .iter()
            .any(|segment| segment.ident == expected),
        Type::Reference(reference) => type_contains_name(&reference.elem, expected),
        _ => false,
    }
}

fn looks_like_rust(code: &str) -> bool {
    code.contains("fn ") || code.contains("pub struct") || code.contains("impl ")
}

fn finding(
    severity: Severity,
    rule_id: &str,
    message: String,
    path: Option<&str>,
    source_ref: Option<&str>,
    suggested_fix: Option<&str>,
) -> Finding {
    Finding {
        severity,
        rule_id: rule_id.to_string(),
        message,
        path: path.map(str::to_string),
        line: None,
        source_ref: source_ref.map(str::to_string),
        suggested_fix: suggested_fix.map(str::to_string),
    }
}

fn finding_with_line(
    severity: Severity,
    rule_id: &str,
    message: String,
    path: Option<&str>,
    line: Option<usize>,
    source_ref: Option<&str>,
    suggested_fix: Option<&str>,
) -> Finding {
    Finding {
        severity,
        rule_id: rule_id.to_string(),
        message,
        path: path.map(str::to_string),
        line,
        source_ref: source_ref.map(str::to_string),
        suggested_fix: suggested_fix.map(str::to_string),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_wrong_island_syntax() {
        let report =
            validate_implementation("<Island client:load />", Some("pages/index.html"), None);
        assert!(!report.valid);
        assert!(report
            .findings
            .iter()
            .any(|finding| finding.rule_id == "pilcrow-wrong-island-syntax"));
    }

    #[test]
    fn accepts_current_load_shape() {
        let report = validate_implementation(
            "pub struct Props {}\npub async fn load(req: Req) -> AppResult<Props> { Ok(Props {}) }",
            Some("pages/index.rs"),
            None,
        );
        assert!(report.valid, "{:?}", report.findings);
    }

    #[test]
    fn accepts_typed_page_load_shape() {
        let report = validate_implementation(
            "pub struct Props {}\npub async fn load(ctx: Page) -> AppResult<Props> { Ok(Props {}) }",
            Some("pages/products/[id].rs"),
            None,
        );
        assert!(report.valid, "{:?}", report.findings);
    }

    #[test]
    fn rejects_non_async_load() {
        let report = validate_implementation(
            "pub struct Props {}\npub fn load(req: Req) -> AppResult<Props> { Ok(Props {}) }",
            Some("pages/index.rs"),
            None,
        );
        assert!(!report.valid);
        assert!(report
            .findings
            .iter()
            .any(|f| f.rule_id == "pilcrow-load-async"));
    }

    #[test]
    fn rejects_invalid_trailing_slash_value() {
        let report = validate_implementation(
            "pub const TRAILING_SLASH: &str = \"redirect\";",
            Some("pages/index.rs"),
            None,
        );
        assert!(!report.valid);
        assert!(report
            .findings
            .iter()
            .any(|f| f.rule_id == "pilcrow-page-option-trailing-slash"));
    }

    #[test]
    fn rejects_layout_with_action() {
        let report = validate_implementation(
            "pub async fn create(req: Req) -> ActionResult { redirect(\"/\") }",
            Some("pages/_layout.rs"),
            None,
        );
        // This should warn about actions in layout
        assert!(report
            .findings
            .iter()
            .any(|f| f.rule_id == "pilcrow-layout-no-actions"
                || f.rule_id == "pilcrow-action-return"));
    }

    #[test]
    fn finding_has_source_ref() {
        let report = validate_implementation(
            "pub fn load(req: Req) -> AppResult<Props> { Ok(Props {}) }",
            Some("pages/index.rs"),
            None,
        );
        let async_finding = report
            .findings
            .iter()
            .find(|f| f.rule_id == "pilcrow-load-async");
        assert!(async_finding.is_some());
        assert!(async_finding.unwrap().source_ref.is_some());
    }

    #[test]
    fn finding_has_line_number_for_wrong_island_syntax() {
        let html = "line1\n<Island client:load />\nline3";
        let report = validate_implementation(html, Some("pages/index.html"), None);
        let f = report
            .findings
            .iter()
            .find(|f| f.rule_id == "pilcrow-wrong-island-syntax")
            .unwrap();
        assert_eq!(f.line, Some(2));
    }

    #[test]
    fn rejects_prerender_const_as_removed() {
        for code in [
            "pub const PRERENDER: bool = true;",
            "pub const PRERENDER: &str = \"true\";",
        ] {
            let report = validate_implementation(code, Some("pages/about.rs"), None);
            assert!(
                report
                    .findings
                    .iter()
                    .any(|f| f.rule_id == "pilcrow-prerender-removed"
                        && f.severity == Severity::Error),
                "expected pilcrow-prerender-removed for `{code}`, got: {:?}",
                report.findings
            );
        }
    }

    #[test]
    fn rejects_revalidate_as_string_literal() {
        let report = validate_implementation(
            "pub const REVALIDATE: &str = \"60\";",
            Some("pages/products/index.rs"),
            None,
        );
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.rule_id == "pilcrow-isr-const-wrong-type"),
            "expected pilcrow-isr-const-wrong-type, got: {:?}",
            report.findings
        );
    }

    #[test]
    fn accepts_revalidate_as_integer_literal() {
        let report = validate_implementation(
            "pub const REVALIDATE: u64 = 60;",
            Some("pages/products/index.rs"),
            None,
        );
        assert!(
            !report
                .findings
                .iter()
                .any(|f| f.rule_id == "pilcrow-isr-const-wrong-type"),
            "unexpected finding: {:?}",
            report.findings
        );
    }

    #[test]
    fn suggests_typed_routes_for_hardcoded_redirect_url() {
        let report = validate_implementation(
            "pub async fn create(req: Req) -> ActionResult { redirect(\"/products\") }",
            Some("pages/products/index.rs"),
            None,
        );
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.rule_id == "pilcrow-typed-routes-suggestion"),
            "expected pilcrow-typed-routes-suggestion, got: {:?}",
            report.findings
        );
    }

    #[test]
    fn does_not_suggest_typed_routes_for_root_redirect() {
        let report = validate_implementation(
            "pub async fn create(req: Req) -> ActionResult { redirect(\"/\") }",
            Some("pages/index.rs"),
            None,
        );
        assert!(
            !report
                .findings
                .iter()
                .any(|f| f.rule_id == "pilcrow-typed-routes-suggestion"),
            "unexpected suggestion for root path: {:?}",
            report.findings
        );
    }

    #[test]
    fn warns_when_revalidate_uses_request_scoped_values_without_cache_vary() {
        let report = validate_implementation(
            r#"
pub const REVALIDATE: u64 = 60;
pub async fn load(req: Req) -> AppResult<Props> {
    let locale = req.headers.get("accept-language");
    Ok(Props {})
}
"#,
            Some("pages/products/index.rs"),
            None,
        );
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.rule_id == "pilcrow-isr-missing-cache-vary"),
            "expected pilcrow-isr-missing-cache-vary, got: {:?}",
            report.findings
        );
    }

    #[test]
    fn no_warning_when_cache_vary_is_declared() {
        let report = validate_implementation(
            r#"
pub const REVALIDATE: u64 = 60;
pub const CACHE_VARY: &[&str] = &["accept-language"];
pub async fn load(req: Req) -> AppResult<Props> {
    let _locale = req.headers.get("accept-language");
    Ok(Props {})
}
"#,
            Some("pages/products/index.rs"),
            None,
        );
        assert!(
            !report
                .findings
                .iter()
                .any(|f| f.rule_id == "pilcrow-isr-missing-cache-vary"),
            "unexpected pilcrow-isr-missing-cache-vary: {:?}",
            report.findings
        );
    }

    #[test]
    fn rejects_duplicate_fsr_s_live_slots() {
        let report = validate_implementation(
            r#"<span s-live="status">Open</span><strong s-live='status'>Open</strong>"#,
            Some("pages/tickets/index.html"),
            None,
        );
        assert!(!report.valid);
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.rule_id == "pilcrow-fsr-duplicate-s-live"),
            "expected pilcrow-fsr-duplicate-s-live, got: {:?}",
            report.findings
        );
    }
}
