use crate::templating::build_config::EnvConfig;

/// Render the `generated_env.rs` file — a `pub mod env` with typed `Public` and `Private`
/// structs, each with a `load() -> Result<Self, std::env::VarError>` constructor.
pub fn render_generated_env_module(config: &EnvConfig) -> String {
    let mut out = String::from("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub mod env {\n");

    // Public struct
    out.push_str("    pub struct Public {\n");
    for var in &config.public {
        let field = EnvConfig::field_name(var, true);
        out.push_str(&format!("        pub {field}: String,\n"));
    }
    out.push_str("    }\n");
    out.push_str("    impl Public {\n");
    out.push_str("        pub fn load() -> Result<Self, ::std::env::VarError> {\n");
    out.push_str("            Ok(Self {\n");
    for var in &config.public {
        let field = EnvConfig::field_name(var, true);
        out.push_str(&format!(
            "                {field}: ::std::env::var({})?,\n",
            rust_str(var)
        ));
    }
    out.push_str("            })\n");
    out.push_str("        }\n");
    // Singleton accessor — loaded once, panics on missing env vars at first call.
    out.push_str("        pub fn global() -> &'static Self {\n");
    out.push_str(
        "            static __ENV: ::std::sync::OnceLock<Public> = ::std::sync::OnceLock::new();\n",
    );
    out.push_str("            __ENV.get_or_init(|| Self::load().expect(\"PUBLIC_* env vars required by Pilcrow.toml are not set\"))\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    // Private struct
    out.push_str("    pub struct Private {\n");
    for var in &config.private {
        let field = EnvConfig::field_name(var, false);
        out.push_str(&format!("        pub {field}: String,\n"));
    }
    out.push_str("    }\n");
    out.push_str("    impl Private {\n");
    out.push_str("        pub fn load() -> Result<Self, ::std::env::VarError> {\n");
    out.push_str("            Ok(Self {\n");
    for var in &config.private {
        let field = EnvConfig::field_name(var, false);
        out.push_str(&format!(
            "                {field}: ::std::env::var({})?,\n",
            rust_str(var)
        ));
    }
    out.push_str("            })\n");
    out.push_str("        }\n");
    // Singleton accessor — loaded once at first call, panics on missing env vars.
    out.push_str("        pub fn global() -> &'static Self {\n");
    out.push_str("            static __ENV: ::std::sync::OnceLock<Private> = ::std::sync::OnceLock::new();\n");
    out.push_str("            __ENV.get_or_init(|| Self::load().expect(\"private env vars required by Pilcrow.toml are not set\"))\n");
    out.push_str("        }\n");
    out.push_str("    }\n");

    out.push_str("}\n");
    out
}

fn rust_str(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_env_module_generates_public_and_private_structs() {
        let config = EnvConfig {
            public: vec!["PUBLIC_API_URL".to_string(), "PUBLIC_APP_NAME".to_string()],
            private: vec!["DATABASE_URL".to_string(), "SECRET_KEY".to_string()],
        };
        let src = render_generated_env_module(&config);

        assert!(src.contains("pub mod env {"));
        assert!(src.contains("pub struct Public {"));
        assert!(src.contains("pub api_url: String"));
        assert!(src.contains("pub app_name: String"));
        assert!(src.contains("pub struct Private {"));
        assert!(src.contains("pub database_url: String"));
        assert!(src.contains("pub secret_key: String"));
        assert!(src.contains("::std::env::var(\"PUBLIC_API_URL\")"));
        assert!(src.contains("::std::env::var(\"DATABASE_URL\")"));
        // global() singleton accessor
        assert!(src.contains("pub fn global() -> &'static Self"));
        assert!(src.contains("OnceLock<Public>"));
        assert!(src.contains("OnceLock<Private>"));
    }

    #[test]
    fn render_env_module_empty_config_is_valid() {
        let src = render_generated_env_module(&EnvConfig::default());
        assert!(src.contains("pub struct Public {"));
        assert!(src.contains("pub struct Private {"));
        // No fields, but should compile.
        assert!(!src.contains("::std::env::var"));
    }

    #[test]
    fn env_field_name_strips_public_prefix() {
        assert_eq!(EnvConfig::field_name("PUBLIC_API_URL", true), "api_url");
        assert_eq!(EnvConfig::field_name("DATABASE_URL", false), "database_url");
        assert_eq!(EnvConfig::field_name("SECRET_KEY", false), "secret_key");
        // No PUBLIC_ prefix on a public var → keep as-is
        assert_eq!(EnvConfig::field_name("API_KEY", true), "api_key");
    }
}
