use crate::templating::codegen::GeneratedPageRoute;

/// Render the `generated_typed_routes.rs` file — a `pub mod routes` with one function
/// per page route.  Static routes return `&'static str`; dynamic routes return `String`.
///
/// Function names are derived from the page module symbol (stripping the `page_` prefix).
/// Parameter names are taken from the route pattern (`:param` segments), in order.
pub fn render_generated_typed_routes_module(entries: &[GeneratedPageRoute]) -> String {
    let mut out = String::from("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub mod routes {\n");

    let mut sorted = entries.to_vec();
    sorted.sort_by(|a, b| a.pattern.cmp(&b.pattern));

    for entry in &sorted {
        let fn_name = entry.symbol.strip_prefix("page_").unwrap_or(&entry.symbol);
        let params = extract_params(&entry.pattern);

        if params.is_empty() {
            let pat = &entry.pattern;
            out.push_str(&format!(
                "    pub fn {fn_name}() -> &'static str {{ \"{pat}\" }}\n"
            ));
        } else {
            let args: String = params
                .iter()
                .map(|p| format!("{p}: &str"))
                .collect::<Vec<_>>()
                .join(", ");
            let fmt_str = build_format_string(&entry.pattern);
            let fmt_args: String = params
                .iter()
                .map(|p| format!(", {p}"))
                .collect::<Vec<_>>()
                .join("");
            out.push_str(&format!(
                "    pub fn {fn_name}({args}) -> String {{ format!(\"{fmt_str}\"{fmt_args}) }}\n"
            ));
        }
    }

    out.push_str("}\n");
    out
}

/// Extract ordered param names from a route pattern like `/products/:id/edit`.
fn extract_params(pattern: &str) -> Vec<String> {
    pattern
        .split('/')
        .filter(|seg| seg.starts_with(':'))
        .map(|seg| seg[1..].to_string())
        .collect()
}

/// Build a `format!` string from a route pattern, replacing `:param` with `{}`.
fn build_format_string(pattern: &str) -> String {
    pattern
        .split('/')
        .map(|seg| {
            if seg.starts_with(':') {
                "{}".to_string()
            } else {
                seg.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn route(pattern: &str, symbol: &str) -> GeneratedPageRoute {
        GeneratedPageRoute {
            pattern: pattern.to_string(),
            template_path: String::new(),
            symbol: symbol.to_string(),
            render_symbol: format!("render_{symbol}"),
            route_params: vec![],
            param_matchers: HashMap::new(),
        }
    }

    #[test]
    fn render_typed_routes_static_returns_static_str() {
        let entries = vec![
            route("/", "page_index"),
            route("/products", "page_products"),
        ];
        let src = render_generated_typed_routes_module(&entries);

        assert!(src.contains("pub fn index() -> &'static str { \"/\" }"));
        assert!(src.contains("pub fn products() -> &'static str { \"/products\" }"));
    }

    #[test]
    fn render_typed_routes_dynamic_returns_string() {
        let entries = vec![route("/products/:id", "page_products_id")];
        let src = render_generated_typed_routes_module(&entries);

        assert!(src.contains("pub fn products_id(id: &str) -> String"));
        assert!(src.contains("format!(\"/products/{}\", id)"));
    }

    #[test]
    fn render_typed_routes_multi_param() {
        let entries = vec![route("/orgs/:org/repos/:repo", "page_orgs_org_repos_repo")];
        let src = render_generated_typed_routes_module(&entries);

        assert!(src.contains("pub fn orgs_org_repos_repo(org: &str, repo: &str) -> String"));
        assert!(src.contains("format!(\"/orgs/{}/repos/{}\", org, repo)"));
    }
}
