import React from 'react';
import { useSilcrowForm } from '@pilcrowjs/react';

export default function IndexPage() {
  const form = useSilcrowForm('submit');

  return (
    <div style={{ fontFamily: 'sans-serif', padding: '2rem', maxWidth: '600px', margin: '0 auto' }}>
      <h1>Welcome to Pilcrow.js!</h1>
      <p style={{ color: '#666' }}>This is a new page generated by create-pilcrow.</p>
      
      <div style={{ border: '1px solid #ddd', padding: '1.5rem', borderRadius: '8px', marginTop: '2rem' }}>
        <h3>Server Action Example</h3>
        <form action={form.action}>
          <input 
            type="text" 
            name="name" 
            placeholder="Enter your name" 
            style={{ padding: '0.5rem', borderRadius: '4px', border: '1px solid #ccc', marginRight: '0.5rem' }}
          />
          <button 
            type="submit" 
            style={{ padding: '0.5rem 1rem', borderRadius: '4px', border: 'none', background: '#0070f3', color: 'white', cursor: 'pointer' }}
          >
            Submit
          </button>
        </form>
        {form.message && (
          <div style={{ marginTop: '1rem', color: '#0070f3', fontWeight: 'bold' }}>
            {form.message}
          </div>
        )}
      </div>
    </div>
  );
}

export const actions = {
  async submit(req: any) {
    const body = await req.formData();
    const name = body.get('name');
    return {
      message: `Hello, ${name || 'stranger'}! Greetings from Elysia + Pilcrow.js server!`
    };
  }
};
