use serde_json::Value;

/// The query that populates `Live` struct fields. Returned from `PilcrowLive::query()`.
pub struct LiveQuery {
    pub sql: &'static str,
    pub params: Vec<Value>,
}

/// Per-field metadata provided by codegen for slot registration.
pub struct LiveFieldRegistration {
    pub slot: &'static str,
    pub column_name: Option<&'static str>,
    pub depends_on: Vec<String>,
    pub promote_after: Option<u32>,
    pub patch_debounce: Option<u32>,
}

/// Implemented on the `Live` struct in a route's `live.rs` file.
///
/// Routekit codegen generates the `from_row()` and `live_fields()` impls automatically.
/// Developers only implement `query()`.
pub trait PilcrowLive: Sized {
    /// Returns the SQL query and bound params used to populate all LiveProp fields.
    fn query(params: &serde_json::Map<String, Value>) -> LiveQuery;

    /// Extract field values from a query result row.
    /// Generated by routekit codegen — developer does not implement this manually.
    fn from_row(
        row: &std::collections::HashMap<String, Value>,
        params: &serde_json::Map<String, Value>,
    ) -> Self;

    /// Returns per-field slot metadata. Generated by routekit codegen.
    fn live_fields(params: &serde_json::Map<String, Value>) -> Vec<LiveFieldRegistration>;
}
