use serde_json::Value;

/// The query that populates `Live` struct fields. Returned from `PilcrowLive::query()`.
pub struct LiveQuery {
    pub sql: &'static str,
    pub params: Vec<Value>,
}

/// Per-field metadata provided by codegen for slot registration.
pub struct LiveFieldRegistration {
    pub slot: &'static str,
    pub column_name: Option<&'static str>,
    pub depends_on: Vec<String>,
    pub patch_debounce: Option<u32>,
}

/// Implemented on the `Live` struct in a route's `live.rs` file.
///
/// Routekit codegen generates the `from_row()`, `live_fields()`, and optionally
/// `route_promote_after()` impls automatically. Developers only implement `query()`.
pub trait PilcrowLive: Sized {
    /// Returns the SQL query and bound params used to populate all LiveProp fields.
    fn query(params: &serde_json::Map<String, Value>) -> LiveQuery;

    /// Extract field values from a query result row.
    /// Generated by routekit codegen — developer does not implement this manually.
    fn from_row(
        row: &std::collections::HashMap<String, Value>,
        params: &serde_json::Map<String, Value>,
    ) -> Self;

    /// Returns per-field slot metadata. Generated by routekit codegen.
    fn live_fields(params: &serde_json::Map<String, Value>) -> Vec<LiveFieldRegistration>;

    /// Route-level promote threshold set via `pub const PROMOTE_AFTER: u32 = N` in `page.rs`.
    ///
    /// When `Some(n)`, the entire route is promoted after `n` hits.
    /// `None` (default) falls back to the watcher config default.
    ///
    /// Generated by routekit codegen when the constant is present; otherwise the
    /// default impl returns `None` so existing routes are unaffected.
    fn route_promote_after() -> Option<u32> {
        None
    }
}
