use super::*;

/// Build an API route manifest from `src/api/**/*.rs`.
pub fn build_generated_api_manifest(
    src_root: impl AsRef<Path>,
    ignored_dirs: &[String],
) -> io::Result<Vec<GeneratedApiRoute>> {
    build_api_routes(src_root, ignored_dirs)?
        .into_iter()
        .map(|route| {
            Ok(GeneratedApiRoute {
                pattern: route.pattern,
                module_path: route.module_path,
                symbol: route.symbol,
            })
        })
        .collect()
}

/// Render a Rust module source for discovered API routes.
///
/// The generated module contains:
/// - `GeneratedApiRoute` (borrowed static fields)
/// - `GENERATED_API_ROUTES` const slice
/// - `generated_api_routes()` accessor
/// - `register_generated_api_routes(...)` fold-based helper for framework glue
pub fn render_generated_api_routes_module(entries: &[GeneratedApiRoute]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedApiRoute {\n");
    out.push_str("    pub pattern: &'static str,\n");
    out.push_str("    pub module_path: &'static str,\n");
    out.push_str("    pub symbol: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const GENERATED_API_ROUTES: &[GeneratedApiRoute] = &[\n");

    let entries_str: String = entries
        .iter()
        .map(|entry| {
            format!(
                "    GeneratedApiRoute {{ pattern: {}, module_path: {}, symbol: {} }},\n",
                rust_string(&entry.pattern),
                rust_string(&entry.module_path),
                rust_string(&entry.symbol),
            )
        })
        .collect();
    out.push_str(&entries_str);

    out.push_str("];\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn generated_api_routes() -> &'static [GeneratedApiRoute] {\n");
    out.push_str("    GENERATED_API_ROUTES\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn register_generated_api_routes<R, F>(router: R, register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedApiRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    GENERATED_API_ROUTES.iter().fold(router, register)\n");
    out.push_str("}\n");

    out
}

/// Generate and write the API routes module to the given `out_file` path.
pub fn write_generated_api_routes_module(
    src_root: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
    ignored_dirs: &[String],
) -> io::Result<Vec<GeneratedApiRoute>> {
    let entries = build_generated_api_manifest(src_root, ignored_dirs)?;
    let source = render_generated_api_routes_module(&entries);

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, source)?;

    Ok(entries)
}
