use super::*;

/// Build a page-route manifest from `src/pages/**/*.html`.
pub fn build_generated_page_manifest(
    src_root: impl AsRef<Path>,
    ignored_dirs: &[String],
    fragment_dirs: &[PathBuf],
) -> io::Result<Vec<GeneratedPageRoute>> {
    let src_root = src_root.as_ref();
    let pages_dir = src_root.join("pages");
    let pages_dir_norm = normalize_path_text(&pages_dir);

    let routes = build_page_routes_with_fragment_dirs(src_root, ignored_dirs, fragment_dirs)?;
    let mut generated = routes
        .into_iter()
        .map(|route| {
            let symbol = build_symbol_name(&route.template_path, &pages_dir_norm);
            let render_symbol = format!("render_{symbol}");
            let route_params = route
                .params
                .iter()
                .map(|name| {
                    let constraint = route.param_constraints.get(name);
                    let rust_type = route_param_rust_type(constraint);
                    GeneratedRouteParam {
                        name: name.clone(),
                        rust_type,
                        optional: route.optional_params.iter().any(|p| p == name),
                        catch_all: route.has_catch_all,
                    }
                })
                .collect();
            let param_matchers: HashMap<String, String> = route
                .param_constraints
                .iter()
                .filter_map(|(name, constraint)| {
                    if let ParameterConstraint::External(matcher) = constraint {
                        Some((name.clone(), matcher.clone()))
                    } else {
                        None
                    }
                })
                .collect();
            GeneratedPageRoute {
                pattern: route.pattern,
                template_path: route.template_path,
                symbol,
                render_symbol,
                route_params,
                param_matchers,
            }
        })
        .collect::<Vec<_>>();

    generated.sort_by(|a, b| {
        a.pattern
            .cmp(&b.pattern)
            .then_with(|| a.template_path.cmp(&b.template_path))
    });

    Ok(generated)
}

/// Build a fragment-route manifest for one configured fragment directory.
///
/// Routes are prefixed with `/{url_prefix}/`; module symbols are `frag_{url_prefix}_{path}`.
pub fn build_generated_fragment_manifest(
    src_root: impl AsRef<Path>,
    fragment_dir: &Path,
    url_prefix: &str,
    ignored_dirs: &[String],
) -> io::Result<Vec<GeneratedPageRoute>> {
    let routes = build_fragment_routes(src_root, fragment_dir, url_prefix, ignored_dirs)?;
    let dir_norm = normalize_path_text(fragment_dir);
    let generated = routes
        .into_iter()
        .map(|route| {
            let symbol = build_fragment_symbol(&route.template_path, &dir_norm, url_prefix);
            GeneratedPageRoute {
                pattern: route.pattern,
                template_path: route.template_path,
                symbol: symbol.clone(),
                render_symbol: format!("render_{symbol}"),
                route_params: vec![],
                param_matchers: HashMap::new(),
            }
        })
        .collect();
    Ok(generated)
}

fn route_param_rust_type(constraint: Option<&ParameterConstraint>) -> String {
    match constraint {
        Some(ParameterConstraint::Int) => "i64",
        Some(ParameterConstraint::UInt) => "u64",
        _ => "String",
    }
    .to_string()
}

/// Render a Rust module source for discovered page routes.
///
/// The generated module contains:
/// - `GeneratedPageRoute` (borrowed static fields)
/// - `GENERATED_PAGE_ROUTES` const slice
/// - `generated_routes()` accessor
/// - `register_generated_routes(...)` helper for framework glue
pub fn render_generated_routes_module(entries: &[GeneratedPageRoute]) -> String {
    let mut out = String::new();

    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedPageRoute {\n");
    out.push_str("    pub pattern: &'static str,\n");
    out.push_str("    pub template_path: &'static str,\n");
    out.push_str("    pub symbol: &'static str,\n");
    out.push_str("    pub render_symbol: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const GENERATED_PAGE_ROUTES: &[GeneratedPageRoute] = &[\n");

    for entry in entries {
        let pattern = rust_string(&entry.pattern);
        let template_path = rust_string(&entry.template_path);
        let symbol = rust_string(&entry.symbol);
        let render_symbol = rust_string(&entry.render_symbol);
        let _ = writeln!(
            out,
            "    GeneratedPageRoute {{ pattern: {pattern}, template_path: {template_path}, symbol: {symbol}, render_symbol: {render_symbol} }},"
        );
    }

    out.push_str("];\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn generated_routes() -> &'static [GeneratedPageRoute] {\n");
    out.push_str("    GENERATED_PAGE_ROUTES\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn register_generated_routes<R, F>(mut router: R, mut register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedPageRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    for route in GENERATED_PAGE_ROUTES {\n");
    out.push_str("        router = register(router, route);\n");
    out.push_str("    }\n");
    out.push_str("    router\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn pilcrow_router<R, F>(router: R, register: F) -> R\n");
    out.push_str("where\n");
    out.push_str("    F: FnMut(R, &'static GeneratedPageRoute) -> R,\n");
    out.push_str("{\n");
    out.push_str("    register_generated_routes(router, register)\n");
    out.push_str("}\n");

    out
}

/// Generate and write the routes module to the given `out_file` path.
pub fn write_generated_routes_module(
    src_root: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
    ignored_dirs: &[String],
    fragment_dirs: &[PathBuf],
) -> io::Result<Vec<GeneratedPageRoute>> {
    let entries = build_generated_page_manifest(src_root, ignored_dirs, fragment_dirs)?;
    let source = render_generated_routes_module(&entries);

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, source)?;

    Ok(entries)
}
