use super::*;

/// Render a Rust module source for build-time compiled Askama templates.
///
/// Modules are sorted alphabetically before processing. Because `layout_*` sorts
/// before `page_*` before `ui_*`, a single pass correctly collects layout field
/// info before it's needed by any page.
pub fn render_generated_templates_module(
    entries: &[TemplateCodegenInput],
) -> io::Result<GeneratedTemplatesModule> {
    let mut ordered = entries.to_vec();
    ordered.sort_by(|a, b| {
        a.module_name
            .cmp(&b.module_name)
            .then_with(|| a.source_path.cmp(&b.source_path))
    });

    // Accumulates layout fields as we encounter layouts that have load().
    // Keyed by layout module name. Single-pass is safe due to alphabetical ordering.
    let mut layout_fields: HashMap<String, Vec<syn::Field>> = HashMap::new();
    let mut layout_fields_map: HashMap<String, LayoutFieldsInfo> = HashMap::new();

    let mut out = String::new();
    out.push_str("// @generated by pilcrow-routekit. Do not edit manually.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct GeneratedTemplateEntry {\n");
    out.push_str("    pub source_path: &'static str,\n");
    out.push_str("    pub module_name: &'static str,\n");
    out.push_str("    pub render_symbol: &'static str,\n");
    out.push_str("}\n\n");

    let mut metadata = Vec::with_capacity(ordered.len());
    let mut load_map = HashMap::new();
    let mut action_map: HashMap<String, Vec<ActionFn>> = HashMap::new();
    let mut page_options_map: HashMap<String, PageOptions> = HashMap::new();
<<<<<<< HEAD
    let mut ssg_config_map: HashMap<String, SsgOpts> = HashMap::new();
=======
>>>>>>> origin/main
    let mut live_fields_map: HashMap<String, Vec<String>> = HashMap::new();
    let mut has_live_fn_map: HashMap<String, bool> = HashMap::new();
    let mut fsr_live_source_map: HashMap<String, String> = HashMap::new();
    let mut fsr_live_fields_map: HashMap<String, Vec<String>> = HashMap::new();
    // fragment_url_prefix → [(leaf_name, module_name)] — built to emit `pub mod fragments`.
    let mut fragment_groups: std::collections::BTreeMap<String, Vec<(String, String)>> =
        std::collections::BTreeMap::new();

    for entry in &ordered {
        let is_layout = entry.module_name.starts_with("layout_");

        // For pages: inject ALL layouts' fields from the chain that have load().
        let extra_fields: Vec<syn::Field> = if !is_layout {
            entry
                .layout_chain
                .iter()
                .flat_map(|lmod| {
                    layout_fields
                        .get(lmod.as_str())
                        .into_iter()
                        .flat_map(|f| f.iter())
                        .cloned()
                })
                .collect()
        } else {
            vec![]
        };

        let instrumented = instrument_frontmatter(
            &entry.rust_frontmatter,
            &entry.template_source,
            &entry.source_path,
            &extra_fields,
            entry.fragment_url_prefix.is_some(),
        )?;
        if instrumented
            .load_signature
            .is_some_and(|sig| sig.wants_page)
            && entry.route_params.is_empty()
        {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "`load(ctx: Page)` in '{}' requires a dynamic route segment such as `[id]`; use `load(req: Req)` for static routes",
                    entry.source_path
                ),
            ));
        }

        // Store layout's own fields so pages that use this layout can inject them.
        if is_layout && instrumented.load_signature.is_some() {
            layout_fields.insert(
                entry.module_name.clone(),
                instrumented.own_syn_fields.clone(),
            );
        }

        // Record the layout-chain↔page field mapping for use by the app module generator.
        if !extra_fields.is_empty() {
            // Collect one entry per layout in the chain that contributed fields.
            let chain: Vec<(String, Vec<String>)> = entry
                .layout_chain
                .iter()
                .filter_map(|lmod| {
                    layout_fields
                        .get(lmod.as_str())
                        .map(|fields| (lmod.clone(), named_field_names(fields)))
                })
                .collect();
            if !chain.is_empty() {
                layout_fields_map.insert(
                    entry.module_name.clone(),
                    LayoutFieldsInfo {
                        chain,
                        page_field_names: named_field_names(&instrumented.own_syn_fields),
                    },
                );
            }
        }

        load_map.insert(entry.module_name.clone(), instrumented.load_signature);

        if !instrumented.actions.is_empty() {
            action_map.insert(entry.module_name.clone(), instrumented.actions.clone());
        }

        if instrumented.page_options != PageOptions::default() {
            page_options_map.insert(entry.module_name.clone(), instrumented.page_options.clone());
        }

        if !instrumented.live_fields.is_empty() {
            live_fields_map.insert(entry.module_name.clone(), instrumented.live_fields.clone());
        }

        if instrumented.has_live_fn {
            has_live_fn_map.insert(entry.module_name.clone(), true);
        }

        // Detect live.rs alongside this page (FSR companion file).
        let live_rs_path = Path::new(&entry.source_path)
            .parent()
            .map(|p| p.join("live.rs"))
            .filter(|p| p.exists());
        if let Some(ref live_path) = live_rs_path {
            let route_params: Vec<String> =
                entry.route_params.iter().map(|p| p.name.clone()).collect();
            let page_route_promote_after = instrumented.page_options.fsr.promote_after;
            let auto_attrs = &instrumented.page_options.fsr.live_field_attrs;
            match crate::fsr::process_live_rs(live_path, &route_params, page_route_promote_after, auto_attrs, &entry.module_name) {
                Ok((src, fields)) => {
                    crate::fsr::validate_live_template_slots(
                        &entry.template_source,
                        &fields,
                        Path::new(&entry.source_path),
                        live_path,
                    )
                    .map_err(|e| {
                        io::Error::new(
                            io::ErrorKind::InvalidData,
                            format!("failed to validate {}: {e}", live_path.display()),
                        )
                    })?;
                    if !fields.is_empty() {
                        fsr_live_fields_map.insert(
                            entry.module_name.clone(),
                            fields.iter().map(|f| f.name.clone()).collect(),
                        );
                    }
                    fsr_live_source_map.insert(entry.module_name.clone(), src);
                }
                Err(e) => {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidData,
                        format!("failed to process {}: {e}", live_path.display()),
                    ));
                }
            }
        }

<<<<<<< HEAD

        if instrumented.page_options.ssg.prerender {
            ssg_config_map.insert(
                entry.module_name.clone(),
                instrumented.page_options.ssg.clone(),
            );
        }
=======
>>>>>>> origin/main

        let module_ident = syn::Ident::new(&entry.module_name, Span::call_site());
        let render_ident = syn::Ident::new(&entry.render_symbol, Span::call_site());

        // When extra_fields is non-empty the module emits __MergedProps for rendering.
        let render_type = if extra_fields.is_empty() {
            "Props"
        } else {
            "__MergedProps"
        };

        let _ = writeln!(out, "#[allow(dead_code)]");
        let _ = writeln!(out, "pub mod {module_ident} {{");
        if !entry.route_params.is_empty() {
            out.push_str(&emit_page_params(&entry.route_params));
        }
        for line in instrumented.source.lines() {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
        // Emit processed live.rs source (FSR companion), if present.
        if let Some(live_src) = fsr_live_source_map.get(&entry.module_name) {
            out.push_str("    // FSR: live.rs companion\n");
            for line in live_src.lines() {
                out.push_str("    ");
                out.push_str(line);
                out.push('\n');
            }
            // Emit FromRequestParts impl for Live.
            out.push_str("    #[::pilcrow_web::axum::async_trait]\n");
            out.push_str("    impl<__S: ::std::marker::Send + ::std::marker::Sync>\n");
            out.push_str("        ::pilcrow_web::axum::extract::FromRequestParts<__S>\n");
            out.push_str("        for Live\n");
            out.push_str("    {\n");
            out.push_str(
                "        type Rejection = (::pilcrow_web::axum::http::StatusCode, String);\n",
            );
            out.push_str("        async fn from_request_parts(\n");
            out.push_str("            parts: &mut ::pilcrow_web::axum::http::request::Parts,\n");
            out.push_str("            _state: &__S,\n");
            out.push_str("        ) -> ::std::result::Result<Self, Self::Rejection> {\n");
            out.push_str(
                "            ::pilcrow_runtime::fsr::extract_live_from_parts(parts).await\n",
            );
            out.push_str("                .map_err(|e| (::pilcrow_web::axum::http::StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))\n");
            out.push_str("        }\n");
            out.push_str("    }\n");
        }
        let _ = writeln!(
            out,
            "    pub fn {render_ident}(props: {render_type}) -> Result<String, askama::Error> {{"
        );
        out.push_str("        askama::Template::render(&props)\n");
        out.push_str("    }\n");

        // Fragment modules get a `pub fn render(props: Props)` alias so callers can write
        // `fragment_mod::render(props)` instead of the full render_frag_*() name.
        if entry.fragment_url_prefix.is_some() {
            let _ = writeln!(
                out,
                "    pub fn render(props: {render_type}) -> Result<String, askama::Error> {{"
            );
            let _ = writeln!(out, "        {render_ident}(props)");
            out.push_str("    }\n");

            // Record for `pub mod fragments` generation below.
            let prefix = entry.fragment_url_prefix.as_deref().unwrap_or("");
            let leaf = fragment_leaf_name(&entry.module_name, prefix);
            fragment_groups
                .entry(prefix.to_string())
                .or_default()
                .push((leaf, entry.module_name.clone()));
        }

        out.push_str("}\n\n");

        metadata.push(GeneratedTemplateEntry {
            source_path: entry.source_path.clone(),
            module_name: module_ident.to_string(),
            render_symbol: render_ident.to_string(),
        });
    }

    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub const GENERATED_TEMPLATES: &[GeneratedTemplateEntry] = &[\n");
    for entry in &metadata {
        let source_path = rust_string(&entry.source_path);
        let module_name = rust_string(&entry.module_name);
        let render_symbol = rust_string(&entry.render_symbol);
        let _ = writeln!(
            out,
            "    GeneratedTemplateEntry {{ source_path: {source_path}, module_name: {module_name}, render_symbol: {render_symbol} }},"
        );
    }
    out.push_str("];\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub fn generated_templates() -> &'static [GeneratedTemplateEntry] {\n");
    out.push_str("    GENERATED_TEMPLATES\n");
    out.push_str("}\n\n");

    // ── pub mod fragments ────────────────────────────────────────────────────
    // Always emit the module (even empty) so `use super::fragments;` always compiles.
    out.push_str("#[allow(dead_code, unused_imports)]\n");
    out.push_str("pub mod fragments {\n");
    for (prefix, mut entries) in fragment_groups {
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        let prefix_mod = sanitize_module_segment(&prefix);
        let _ = writeln!(out, "    #[allow(unused_imports)]");
        let _ = writeln!(out, "    pub mod {prefix_mod} {{");
        for (leaf, module_name) in &entries {
            let _ = writeln!(
                out,
                "        pub use super::super::{module_name} as {leaf};"
            );
        }
        out.push_str("    }\n");
    }
    out.push_str("}\n");

    Ok(GeneratedTemplatesModule {
        source: out,
        entries: metadata,
        load_map,
        layout_fields_map,
        action_map,
        page_options: page_options_map,
<<<<<<< HEAD
        ssg_config_map,
=======
>>>>>>> origin/main
        live_fields_map,
        has_live_fn_map,
        fsr_live_source_map,
        fsr_live_fields_map,
    })
}

fn emit_page_params(params: &[GeneratedRouteParam]) -> String {
    let mut out = String::new();
    out.push_str("    #[derive(Debug, Clone, serde::Serialize)]\n");
    out.push_str("    pub struct Params {\n");
    for param in params {
        let ty = if param.catch_all {
            "Vec<String>".to_string()
        } else if param.optional {
            format!("Option<{}>", param.rust_type)
        } else {
            param.rust_type.clone()
        };
        let _ = writeln!(out, "        pub {}: {},", param.name, ty);
    }
    out.push_str("    }\n");
    out.push_str("    pub type Page = ::pilcrow_web::Page<Params>;\n");
    out.push_str("    impl ::std::convert::TryFrom<::std::collections::HashMap<String, String>> for Params {\n");
    out.push_str("        type Error = ::pilcrow_web::AppError;\n");
    out.push_str("        fn try_from(mut __params: ::std::collections::HashMap<String, String>) -> ::std::result::Result<Self, Self::Error> {\n");
    out.push_str("            Ok(Self {\n");
    for param in params {
        let name_lit = rust_string(&param.name);
        let field = &param.name;
        if param.catch_all {
            let _ = writeln!(
                out,
                "                {field}: __params.remove({name_lit}).map(|v| v.split('/').map(|s| s.to_string()).collect()).unwrap_or_default(),"
            );
        } else if param.optional {
            let parse = parse_param_expr(&param.rust_type, "__value");
            let _ = writeln!(
                out,
                "                {field}: match __params.remove({name_lit}) {{ Some(__value) if !__value.is_empty() => Some({parse}), _ => None }},"
            );
        } else {
            let parse = parse_param_expr(&param.rust_type, "__value");
            let _ = writeln!(
                out,
                "                {field}: {{ let __value = __params.remove({name_lit}).ok_or_else(|| ::pilcrow_web::AppError::NotFound({name_lit}.to_string()))?; {parse} }},"
            );
        }
    }
    out.push_str("            })\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out
}

fn parse_param_expr(rust_type: &str, value_ident: &str) -> String {
    match rust_type {
        "i64" | "u64" => format!(
            "{value_ident}.parse::<{rust_type}>().map_err(|_| ::pilcrow_web::AppError::NotFound)?"
        ),
        _ => value_ident.to_string(),
    }
}

/// Generate and write the compiled templates module to `out_file`.
pub fn write_generated_templates_module(
    entries: &[TemplateCodegenInput],
    out_file: impl AsRef<Path>,
) -> io::Result<WrittenTemplatesOutput> {
    let generated = render_generated_templates_module(entries)?;

    let out_file = out_file.as_ref();
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, generated.source)?;

    Ok(WrittenTemplatesOutput {
        entries: generated.entries,
        load_map: generated.load_map,
        layout_fields_map: generated.layout_fields_map,
        action_map: generated.action_map,
        page_options: generated.page_options,
<<<<<<< HEAD
        ssg_config_map: generated.ssg_config_map,
=======
>>>>>>> origin/main
        live_fields_map: generated.live_fields_map,
        has_live_fn_map: generated.has_live_fn_map,
        fsr_live_source_map: generated.fsr_live_source_map,
        fsr_live_fields_map: generated.fsr_live_fields_map,
    })
}
